### ISSUE TITLE
can't install schema.json via about:debugging

### ISSUE THREAD

**Issue by ghost** [Koushien/keyboard-shortcut-api#5]
Hi, when loading keyboard-shortcut-api/schema.json via about:debugging I get the following:

`There was an error during installation: Install manifest specifies unknown type: null`

Tested with latest Nightly and extensions.legacy.enabled true. Is this experimental API no longer available?

**Comment by Koushien** [comment]
I found your bug report in https://bugzilla.mozilla.org/show_bug.cgi?id=1477866 while I was looking into Experiments changes. As you probably figured out there's a new way to develop WebExtensions Experiments and support for the old system was pulled in April https://hg.mozilla.org/mozilla-central/rev/bc2f1762365b?revcount=240. I recall chatter about this being planned last year in Mozilla's IRC.

You can remove the `permissions` property in `schema.json` and use this `test-extension/manifest.json`
```json
{

  "manifest_version": 2,
  "name": "Keyboard Shortcut Tester",
  "version": "0.0.1",
  "experiment_apis": {
    "keyboard_shortcut": {
      "schema": "../schema.json",
      "parent": {
        "scopes": [ "addon_parent" ],
        "paths": [ ["keyboard_shortcut"] ],
        "script": "../api.js"
      }
    }
  },

  "background" : { "scripts": ["main.js"] },

  "browser_action": {
    "default_title": "Keyboard Shortcut Tester",
    "browser_style": true
  },

  "applications": {
    "gecko": {
      "id": "keyboard_shortcut_tester@example.org",
      "strict_min_version": "60.0"
    }
  }
}
```

This allows you to install the test extension which ends up installing the Keyboard Shortcut API.
Presumably you can make use of the API in your own extension by placing `"permissions": [ "experiments.keyboard_shortcut" ]` in your `manifest.json`, but since the test extension is no longer functional itself I'm not sure if `api.js` needs changes for you to make use of it.

**Comment by ghost** [comment]
Thanks for your pointers, very much appreciated. At least I got a chance to install this due to your help and follow the code logic. I was looking for an easy way to trigger the 'Focus location bar' shortcut but couldn't get that working. Learned a lot though by looking at the code here, so thanks again for your detailed response.
